"""Rich-turn engine backed by a real AI provider.

`ConversationService.post_message` is a synchronous write path (it drives a
synchronous SQLAlchemy session from a threadpool worker). A real provider's
orchestrator is async. This adapter bridges the two so the existing
non-streaming endpoint keeps producing genuine model output when
`AI_PROVIDER` is a real provider, instead of breaking or falling back to the
simulator.

Two details that matter:

* The provider is built **fresh per call** and never cached. `asyncio.run`
  closes the loop it creates, and an SDK HTTP client is bound to the loop it
  was constructed on; reusing a cached client across loops would fail in a
  confusing, intermittent way. The streaming path (the primary one) keeps the
  cached, loop-stable provider.
* The rich-turn vocabulary is preserved by wrapping the model's text in a
  single `TextBlock`, so the transcript shape the UI reads is unchanged
  regardless of which provider produced it.
"""

from __future__ import annotations

import asyncio

from app.ai.errors import AIError
from app.ai.factory import build_provider
from app.ai.orchestrator import AIOrchestrator
from app.ai.types import ChatMessage
from app.core.config import settings
from app.schemas.blocks import TextBlock
from app.services.engine.base import EngineRequest, EngineError, EngineTurn

# The simulator's rich block vocabulary has no analogue in a plain text model.
# A real provider therefore returns a single text block; the UI renders that
# natively, so nothing downstream needs to know which provider answered.
_DEFAULT_REASONING = "Generated by the configured model provider."


class AIEngine:
    """`Engine` implementation that calls a real provider."""

    def __init__(self, provider_name: str | None = None) -> None:
        self.name = (provider_name or settings.AI_PROVIDER).strip().lower()

    def generate(self, request: EngineRequest) -> EngineTurn:
        # Runs the async orchestrator on a private event loop. Safe here because
        # sync routes execute in a threadpool worker with no loop running.
        try:
            result = asyncio.run(self._generate(request))
        except AIError as exc:
            # Translated to the engine's own error so the service can answer
            # with its established 503 behaviour and code.
            raise EngineError(exc.message) from exc

        if not result.text.strip():
            raise EngineError("The provider returned an empty response.")
        return EngineTurn(
            reasoning=_DEFAULT_REASONING,
            traces=[],
            blocks=[TextBlock(body=result.text)],
            mode_id=request.mode_id,
            tokens=result.usage.total_tokens or 0,
            route=f"{result.provider}:{result.model}",
        )

    async def _generate(self, request: EngineRequest):
        provider = build_provider(self.name)
        orchestrator = AIOrchestrator(provider)
        history = [
            ChatMessage(role="user", content=prompt) for prompt in request.history
        ]
        return await orchestrator.generate(
            history=history,
            current_user_message=request.prompt,
        )


__all__ = ["AIEngine"]
