"""add AI provenance columns and the usage ledger

Revision ID: 0003_ai_integration
Revises: 0002_auth_identity
Create Date: 2026-09-27 00:00:00.000000

Additive only. No existing table is dropped, retyped or renamed, and every new
`messages` column is nullable or has a server default, so pre-STEP-6 rows stay
valid without a backfill:

* `status` defaults to 'completed' — which is exactly what every historical
  message is, since nothing before STEP 6 could fail mid-generation.
* the provenance columns (`model`, `provider`, tokens, `latency_ms`,
  `error_code`, `idempotency_key`) are NULL for existing rows, which is the
  honest value: they were never generated by a provider.
* `ai_usage_events` is new, so there is nothing to migrate.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0003_ai_integration"
down_revision: str | None = "0002_auth_identity"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── Message provenance (STEP 6) ───────────────────────────────────
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=16),
                nullable=False,
                server_default="completed",
            )
        )
        batch_op.add_column(sa.Column("model", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("provider", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("input_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("output_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("total_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("latency_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("error_code", sa.String(length=48), nullable=True))
        batch_op.add_column(
            sa.Column("idempotency_key", sa.String(length=80), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_messages_idempotency_key"), ["idempotency_key"], unique=False
        )

    # ── AI usage ledger ───────────────────────────────────────────────
    # No foreign keys on user_id/conversation_id on purpose: a usage record is
    # an accounting fact and must survive deletion of what it describes.
    op.create_table(
        "ai_usage_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("conversation_id", sa.String(length=64), nullable=True),
        sa.Column("message_id", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("time_to_first_token_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("pricing_version", sa.String(length=32), nullable=True),
        sa.Column("request_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_usage_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_usage_events_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_events_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_events_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_events_model"), ["model"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_events_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_ai_usage_user_time", ["user_id", "request_started_at"], unique=False
        )
        batch_op.create_index(
            "ix_ai_usage_status_time", ["status", "request_started_at"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("ai_usage_events", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_usage_status_time")
        batch_op.drop_index("ix_ai_usage_user_time")
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_status"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_model"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_provider"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_user_id"))

    op.drop_table("ai_usage_events")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_idempotency_key"))
        batch_op.drop_column("idempotency_key")
        batch_op.drop_column("error_code")
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("total_tokens")
        batch_op.drop_column("output_tokens")
        batch_op.drop_column("input_tokens")
        batch_op.drop_column("provider")
        batch_op.drop_column("model")
        batch_op.drop_column("status")
