-- AURELIS Intelligence API — Supabase core schema.
-- Migration 0001; follows the migration rules in ../README.md:
--   * idempotent (safe to replay)
--   * tables created without FKs so ordering never matters
--   * constraints, FKs and indexes added afterwards
--
-- This mirrors backend/alembic/versions/0001_module2_core_schema.py so the
-- Supabase deployment and the SQLite/Alembic deployment hold the same shape.

create table if not exists ai_modes (
    id          text primary key,
    label       text not null,
    caption     text not null,
    description text not null,
    aura        text not null,          -- "r g b" triple read by the UI's rgba() helper
    glyph       text not null,
    sort_order  integer not null default 0,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create table if not exists daily_usage (
    id         bigint generated by default as identity primary key,
    day        date not null,
    label      text not null,
    value      integer not null default 0,
    secondary  integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists knowledge_sources (
    id             text primary key,
    name           text not null,
    kind           text not null,       -- document | repository | dataset | feed
    status         text not null,       -- indexed | indexing | paused
    item_count     integer not null default 0,
    last_synced_at timestamptz,
    sort_order     integer not null default 0,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create table if not exists memory_records (
    id          text primary key,
    statement   text not null,
    scope       text not null,
    confidence  double precision not null default 0,
    learned_at  timestamptz not null,
    owner_id    text,                   -- populated once MODULE 4 defines identity
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create table if not exists projects (
    id         text primary key,
    name       text not null,
    brief      text not null,
    progress   double precision not null default 0,
    accent     text not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists tool_integrations (
    id         text primary key,
    name       text not null,
    category   text not null,
    connected  boolean not null default false,
    permission text not null,
    call_count integer not null default 0,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists activity_events (
    id          bigint generated by default as identity primary key,
    label       text not null,
    mode_id     text not null,
    occurred_at timestamptz not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create table if not exists conversations (
    id              text primary key,
    title           text not null,
    preview         text not null default '',
    mode_id         text not null,
    project_id      text,
    pinned          boolean not null default false,
    archived        boolean not null default false,
    message_count   integer not null default 0,
    last_message_at timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table if not exists messages (
    id              text primary key,
    conversation_id text not null,
    position        integer not null,   -- monotonic within a conversation
    role            text not null,
    mode_id         text not null,
    blocks          jsonb not null default '[]'::jsonb,
    reasoning       text,
    traces          jsonb,
    voice           boolean not null default false,
    tokens          integer,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- ── Constraints ───────────────────────────────────────────────────────────
-- Added separately and guarded, because `create table if not exists` skips
-- the whole statement when the table already exists — including any inline
-- constraints — so an inline constraint would silently never appear on a
-- replay against a partially-created database.

do $$
begin
    alter table daily_usage add constraint uq_daily_usage_day unique (day);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table messages
        add constraint uq_messages_thread_pos unique (conversation_id, position);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table activity_events
        add constraint fk_activity_events_mode_id
        foreign key (mode_id) references ai_modes (id) on delete restrict;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table conversations
        add constraint fk_conversations_mode_id
        foreign key (mode_id) references ai_modes (id) on delete restrict;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table conversations
        add constraint fk_conversations_project_id
        foreign key (project_id) references projects (id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table messages
        add constraint fk_messages_conversation_id
        foreign key (conversation_id) references conversations (id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table messages
        add constraint fk_messages_mode_id
        foreign key (mode_id) references ai_modes (id) on delete restrict;
exception when duplicate_object then null;
end $$;

-- ── Indexes ───────────────────────────────────────────────────────────────
create index if not exists ix_activity_events_mode_id       on activity_events (mode_id);
create index if not exists ix_activity_events_occurred_at   on activity_events (occurred_at);
create index if not exists ix_conversations_last_message_at on conversations (last_message_at);
create index if not exists ix_conversations_mode_id         on conversations (mode_id);
create index if not exists ix_conversations_project_id      on conversations (project_id);
create index if not exists ix_conversations_recent          on conversations (archived, last_message_at);
create index if not exists ix_knowledge_sources_kind        on knowledge_sources (kind);
create index if not exists ix_knowledge_sources_last_synced_at on knowledge_sources (last_synced_at);
create index if not exists ix_knowledge_sources_status      on knowledge_sources (status);
create index if not exists ix_memory_records_learned_at     on memory_records (learned_at);
create index if not exists ix_memory_records_owner_id       on memory_records (owner_id);
create index if not exists ix_memory_records_scope          on memory_records (scope);
create index if not exists ix_messages_conversation_id      on messages (conversation_id);
create index if not exists ix_tool_integrations_category    on tool_integrations (category);

-- ── updated_at maintenance ────────────────────────────────────────────────
-- The ORM sets updated_at client-side, but rows can also be written through
-- PostgREST or the dashboard, which bypass the ORM entirely. A trigger keeps
-- the column truthful regardless of the write path.
create or replace function set_updated_at() returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

do $$
declare
    t text;
begin
    foreach t in array array[
        'ai_modes', 'daily_usage', 'knowledge_sources', 'memory_records',
        'projects', 'tool_integrations', 'activity_events', 'conversations',
        'messages'
    ] loop
        execute format('drop trigger if exists trg_%s_updated_at on %I', t, t);
        execute format(
            'create trigger trg_%s_updated_at before update on %I '
            'for each row execute function set_updated_at()', t, t);
    end loop;
end $$;
