-- AURELIS Intelligence API — identity, sessions and the authentication audit.
-- Migration 0003; follows the rules in ../README.md:
--   * idempotent (safe to replay)
--   * tables created without FKs so ordering never matters
--   * constraints, FKs and indexes added afterwards
--
-- Mirrors backend/alembic/versions/0002_auth_identity.py so the Supabase
-- deployment and the SQLite/Alembic deployment hold the same shape.

-- ── Identity ──────────────────────────────────────────────────────────────
create table if not exists users (
    id                 uuid primary key default gen_random_uuid(),
    full_name          text not null,
    -- Stored lowercased and trimmed. The unique index below is what actually
    -- prevents duplicates; a check-then-insert alone would race.
    email              text not null,
    -- Argon2id encoded digest. Never a plaintext password, never reversible.
    password_hash      text not null,
    -- Server-owned. Never accepted from a request body.
    role               text not null default 'user',
    is_active          boolean not null default true,
    avatar_url         text,
    email_verified     boolean not null default false,
    last_login_at      timestamptz,
    failed_login_count integer not null default 0,
    locked_until       timestamptz,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now(),
    constraint ck_users_role check (role in ('user', 'admin'))
);

create table if not exists user_preferences (
    id            bigint generated by default as identity primary key,
    user_id       uuid not null,
    ambient_light boolean not null default true,
    particles     boolean not null default true,
    reduce_motion boolean not null default false,
    streaming     boolean not null default true,
    memory        boolean not null default true,
    citations     boolean not null default true,
    soundscape    boolean not null default false,
    density       text not null default 'comfortable',
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    constraint ck_user_preferences_density check (density in ('comfortable', 'compact'))
);

-- ── Sessions and reset tokens (digests only) ──────────────────────────────
-- Only the SHA-256 digest of a refresh token is stored, so a database leak
-- does not hand over usable tokens. Rotation and revocation are row updates.
create table if not exists auth_sessions (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid not null,
    token_hash   text not null,
    expires_at   timestamptz not null,
    revoked_at   timestamptz,
    last_used_at timestamptz,
    user_agent   text,
    -- HMAC digest of the client address, not the address itself.
    ip_hash      text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create table if not exists password_reset_tokens (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null,
    token_hash text not null,
    expires_at timestamptz not null,
    used_at    timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ── Audit trail ───────────────────────────────────────────────────────────
-- `user_id` carries no foreign key on purpose: the security record must
-- outlive the account it describes. Only keyed digests of the email and
-- address are stored, never the values.
create table if not exists auth_events (
    id          bigint generated by default as identity primary key,
    user_id     uuid,
    event_type  text not null,
    outcome     text not null default 'success',
    email_hash  text,
    ip_hash     text,
    user_agent  text,
    detail      text,
    occurred_at timestamptz not null default now(),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    constraint ck_auth_events_outcome check (outcome in ('success', 'failure', 'denied'))
);

-- ── Ownership on existing content ─────────────────────────────────────────
-- Nullable so the MODULE 2 demo rows stay valid. NULL means "owned by nobody",
-- and the application treats that as invisible to every caller.
alter table conversations add column if not exists owner_id uuid;

-- ── Constraints ───────────────────────────────────────────────────────────
do $$
begin
    alter table users add constraint uq_users_email unique (email);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table user_preferences
        add constraint uq_user_preferences_user_id unique (user_id);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table user_preferences
        add constraint fk_user_preferences_user_id
        foreign key (user_id) references users (id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table auth_sessions
        add constraint uq_auth_sessions_token_hash unique (token_hash);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table auth_sessions
        add constraint fk_auth_sessions_user_id
        foreign key (user_id) references users (id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$
begin
    alter table password_reset_tokens
        add constraint uq_password_reset_tokens_token_hash unique (token_hash);
exception when duplicate_table then null; when duplicate_object then null;
end $$;

do $$
begin
    alter table password_reset_tokens
        add constraint fk_password_reset_tokens_user_id
        foreign key (user_id) references users (id) on delete cascade;
exception when duplicate_object then null;
end $$;

-- Deleting an account takes its threads with it; messages follow through the
-- existing `fk_messages_conversation_id ... on delete cascade`.
do $$
begin
    alter table conversations
        add constraint fk_conversations_owner_id
        foreign key (owner_id) references users (id) on delete cascade;
exception when duplicate_object then null;
end $$;

-- ── Indexes ───────────────────────────────────────────────────────────────
create index if not exists ix_users_email             on users (email);
create index if not exists ix_users_role              on users (role);
create index if not exists ix_users_is_active         on users (is_active);
create index if not exists ix_users_role_active       on users (role, is_active);
create index if not exists ix_auth_sessions_user_id   on auth_sessions (user_id);
create index if not exists ix_auth_sessions_token_hash on auth_sessions (token_hash);
create index if not exists ix_auth_sessions_expires_at on auth_sessions (expires_at);
create index if not exists ix_auth_sessions_user_active on auth_sessions (user_id, revoked_at);
create index if not exists ix_password_reset_tokens_user_id on password_reset_tokens (user_id);
create index if not exists ix_password_reset_tokens_token_hash on password_reset_tokens (token_hash);
create index if not exists ix_password_reset_tokens_expires_at on password_reset_tokens (expires_at);
create index if not exists ix_auth_events_user_id     on auth_events (user_id);
create index if not exists ix_auth_events_event_type  on auth_events (event_type);
create index if not exists ix_auth_events_email_hash  on auth_events (email_hash);
create index if not exists ix_auth_events_occurred_at on auth_events (occurred_at);
create index if not exists ix_auth_events_type_time   on auth_events (event_type, occurred_at);
create index if not exists ix_conversations_owner_id  on conversations (owner_id);

-- ── updated_at maintenance ────────────────────────────────────────────────
-- Reuses `set_updated_at()` from migration 0001, which is `create or replace`
-- there and so is guaranteed to exist by the time this file runs.
do $$
declare
    t text;
begin
    foreach t in array array[
        'users', 'user_preferences', 'auth_sessions',
        'password_reset_tokens', 'auth_events'
    ] loop
        execute format('drop trigger if exists trg_%s_updated_at on %I', t, t);
        execute format(
            'create trigger trg_%s_updated_at before update on %I '
            'for each row execute function set_updated_at()', t, t);
    end loop;
end $$;

-- ── Row Level Security ────────────────────────────────────────────────────
-- Enabled deny-by-default, matching migration 0002. `users` holds password
-- digests, so it is the last table that should ever be reachable from the
-- browser with the anon key.
alter table users                enable row level security;
alter table user_preferences     enable row level security;
alter table auth_sessions        enable row level security;
alter table password_reset_tokens enable row level security;
alter table auth_events          enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Reference data stays publicly readable so the SPA can theme itself before
-- login (re-asserted here because the blanket revoke above strips it again).
grant select on ai_modes to anon, authenticated;

-- ── Note for MODULE 5 ─────────────────────────────────────────────────────
-- No per-user policies are added. The API is the only client: it authenticates
-- with its own Postgres role and enforces ownership in SQLAlchemy. Adding RLS
-- policies would be the right move only once a browser talks to PostgREST
-- directly with a user's JWT, which is not this architecture. Until then,
-- deny-by-default plus a revoke is the correct posture — it means an
-- accidental `using (true)` policy is not the only thing protecting the data.
